// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "SilentVoice",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "SilentVoice",
            targets: ["AppModule"],
            bundleIdentifier: "BoyondModem.SilentVoice",
            teamIdentifier: "PDC26G258Q",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .speechRecognition(purposeString: "Unknown Usage Description"),
                .microphone(purposeString: "Unknown Usage Description")
            ],
            appCategory: .healthcareFitness
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
